Repository Re-Spring/Do-Rering_AI, pull requests merged in 2024-02, with the labels that each got.

#2 'voiceclone-001'
  VoiceClone/templates/cloneHome.html
  VoiceClone/templates/dubbing.html
  VoiceClone/templates/recording.html
  VoiceClone/voiceClone.py
Labels: bug

#14 [FEATURE] openAI dalle3 API 일관성 테스트
  T2I/dalle3.py
  templates/T2I/dalle.html
Labels: ⚙️ feature

#13 [Feature] 동화 생성 프롬프트 고도화
  LLM/LLM.py
Labels: ⚙️ feature

#18 [Feature] 더빙 API streamlit을 fastAPI로 바꿈
  DubingAPI/voice.py
  static/DubingAPI_audio/2024-02-27_16-06-13.mp3
  templates/Dubing/dubing.html
Labels: ⚙️ Feature

#17 [Feature] prompt normalization
  LLM/LLM.py
  static/LLM/images/output_0.png
  static/LLM/images/output_1.png
  static/LLM/images/output_10.png
  static/LLM/images/output_11.png
  static/LLM/images/output_12.png
  static/LLM/images/output_13.png
  static/LLM/images/output_2.png
  static/LLM/images/output_3.png
  static/LLM/images/output_4.png
  static/LLM/images/output_5.png
  static/LLM/images/output_6.png
  static/LLM/images/output_7.png
  static/LLM/images/output_8.png
  static/LLM/images/output_9.png
  static/LLM/js/main.js
Labels: ⚙️ Feature

#20 [Feature] voiceCloneDubbing 모듈화
  .idea/misc.xml
  VoiceClone/Dubbing/dubbing.py
  VoiceClone/VoiceCloning/voiceCloning.py
Labels: ⚙️ Feature
